config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tournaments, only: [:index, :new, :create, :show, :destroy]
  resources :players
  resources :games, only: [:show]
  resources :rounds, only: [:show]
  patch '/games/:id', to: 'games#set_winner'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: [:new, :create]
  resources :ranks, only: [:index]
  root 'welcome#root'
  get "/home", to: "welcome#home"
  get "/search", to: "players#search"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :games_as_p1, class_name: :Game, foreign_key: :p1_id
  has_many :games_as_p2, class_name: :Game, foreign_key: :p2_id
  has_many :rounds, through: :games
  has_many :tournaments, through: :rounds
  validates :nickname, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def name
    self.first_name.capitalize + " " + self.last_name.capitalize
  end

  def games
    self.games_as_p1 + self.games_as_p2
  end

  def win?(game)
    if game.winner == self
      "won"
    elsif game.loser == self
      "lost"
    else
      "playing"
    end
  end

  def self.active_players
    self.all.select do |player|
      player.active
    end
  end

  def add_point
    self.update(points: (self.points + 1))
  end

  def self.ranks
    ranks = []
    ranks = Player.active_players.sort_by {|player| player.points}
    return ranks.reverse
  end

  def game_win_percentage
    games = self.games.select do |game|
      game.status == "Completed"
    end
    games_played = games.count
    if games_played == 0
      "No Stats"
    else
      games_won = 0
      games.each do |game|
        if game.winner == self
          games_won+=1
        end
      end

      percent = ( games_won.to_f/games_played)*100
    return percent.to_s + "%"
    end
  end

  def tour_win_percentage
    tourn = self.games.select do |game|
      game.round.tournament.status == "Completed"
    end
    tour_played = tourn.uniq.count
    if tour_played == 0
      "No Stats"
    else
      tour_won = 0
      tourn.uniq.each do |tour|
        if tour.winner_id == self.id
          tour_won+=1
        end
      end

      percent = ( tour_won.to_f/tour_played)*100
      return percent.to_s + "%"
    end
  end

  def default_image
    arr = ["cat1.jpg", "cat2.jpg", "cat3.jpg", "cat4.jpg", "cat7.jpeg", "dog1.png", "dog2.png", "dog3.jpg",
            "dog4.jpg", "dog6.jpg", "horse.jpg", "lizard.jpg", "monkey.jpg", "squirrel.jpg"]
    self.img_url = arr.sample
  end


end

app/controllers/players_controller.rb
require 'open-uri'
class PlayersController < ApplicationController

  before_action :find_player, only: [:show, :edit, :update, :destroy]
  before_action :authorized

  def index
    @players = Player.active_players
  end

  def show
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      @player.active = true
      @player.save
      if @player.img_url.empty? || asset_exists?(@player.img_url) == false
        @player.default_image
        @player.save
      end
      redirect_to player_path(@player)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @player.update(player_params)
    redirect_to player_path(@player)
  end

  def search
    search = params[:q]


    @players = []
    Player.all.each do |player|

      if (player.first_name.downcase == search.downcase || player.last_name.downcase == search.downcase || player.nickname.downcase == search.downcase) && player.active == true
        @players<< player
      end
    end

    if @players.empty?

      @players = Player.active_players
    end
  render :index
  end

  def destroy
    @player.active = false
    @player.save
    redirect_to players_path
  end

  private

  def player_params
    # params.require(:player).permit(:first_name, :last_name, :nickname, :img_url).merge(active: true)
    params.require(:player).permit(:first_name, :last_name, :nickname, :img_url)

  end

  def find_player
    @player = Player.find(params[:id])
  end

  def asset_exists?(path)
    begin
      pathname = Rails.application.assets.resolve(path) || image?(path)
      return !!pathname # double-bang turns String into boolean
    # rescue Sprockets::FileNotFound
    #   return false
    end
  end

  def image?(uri)
    begin
      str = open(uri)
      return str.content_type.start_with?("image")
    rescue
      return false
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_players_form.html.erb
<% if @player.errors.any? %>
 <div class="box" id=“error_explanation”>
   <h2>
     <%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved!
   </h2>
   <ul>
     <% @player.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
   </ul>
 </div>
<% end %>

<div class="box">

  <%= form_for @player, :html => {:class => "ui form"} do |f| %>
  <div class="two fields">
    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div><div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
  </div>
  <div class="two fields">
    <div class="field">
      <%= f.label :nickname %>
      <%= f.text_field :nickname %>
    </div><div class="field">
      <%= f.label :img_url %>
      <%= f.text_field :img_url %>
    </div>
  </div>
      <%= f.submit "Submit", class: "circular ui inverted button"  %>
  <% end %>
</div>

app/views/players/edit.html.erb
<h1>Edit <%= @player.nickname %>!</h1>

<%= render "players_form" %>

app/views/players/index.html.erb
<h1>All Players</h1>
<div class="box">
    <%= form_tag("/search", method: "get") do %>
      <div class="ui search">
      <%= text_field_tag(:q, nil, placeholder: "Search for Player", class: "prompt") %>
      <%= submit_tag "Search", class: "circular ui inverted button"%>
    </div>
    <% end %>
<ul>
  <% @players.each do |player| %>
    <li class="large-selection"><%= link_to image_tag(player.img_url, width: 100, height: 100, class: "person", alt: player.name), player_path(player)  %>
    <%=link_to player.name, player, class: "ui inverted button" %></li>
  <% end %>
</ul>
</div>

app/views/players/new.html.erb
<h1>Create a Player!</h1>

<%= render "players_form" %>

app/views/players/show.html.erb
<ul>
  <li class="large-selection"><%= image_tag(@player.img_url, width: 60, height: 60, class: "person")  %></li>
  <li class="large-selection"><h1><%= @player.nickname %></h1>
    <h3><%= @player.name %></h3></li>
</ul>

<div class="box">
    <% if !@player.games.empty? %>
    <div class="tables">
    <table class="ui celled structured table">
      <thead>
        <tr>
          <th colspan="3">Games</th>
        </tr>
        <tr>
          <th>Tournament</th>
          <th>Round</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
        <% @player.games.each do |game| %>
        <tr>
          <% if game.round.tournament.user.id != session["user_id"] %>
            <td><%= game.round.tournament.name %></td>
          <% else %>
            <td> <%= link_to game.round.tournament.name, game.round.tournament %> </td>
          <% end %>
          <td> <%= game.round.num %> </td>
          <% if @player.win?(game) == "won" %>
          <td class="positive"><i class="icon checkmark"></i> <%= @player.win?(game) %> </td>
          <% elsif @player.win?(game) == "lost" %>
          <td class="negative"> <%= @player.win?(game) %> </td>
          <% else %>
          <td> Playing </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>

    <table class="ui celled structured table">
      <thead>
        <tr>
          <th colspan="3">Stats</th>
        </tr>
        <tr>
          <th>Game Win Percentage</th>
          <th>Tournament Win Percentage</th>
          <th>Points</th>
        </tr>
      </thead>
      <tbody>
        <td><%= @player.game_win_percentage %></td>
        <td><%= @player.tour_win_percentage %></td>
        <td><%= @player.points %></td>
      </tbody>

    </table>
  </div>
  <% else %>
  <p> <%= @player.name %> hasn't played any games yet!</p>
  <% end %>



</div>
<ul>
  <li class="large-selection">
    <%= link_to "Edit player", edit_player_path ,  class: "circular ui inverted button deletion" %>
  </li>
  <li class="large-selection">
    <%= form_tag @player, method: "delete" do %>
    <%= submit_tag "Delete Player", class: "circular ui inverted button deletion" %>
    <% end %>
  </li>
</ul>