config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tournaments, only: [:index, :new, :create, :show, :destroy]
  resources :players
  resources :games, only: [:show]
  resources :rounds, only: [:show]
  patch '/games/:id', to: 'games#set_winner'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: [:new, :create]
  resources :ranks, only: [:index]
  root 'welcome#root'
  get "/home", to: "welcome#home"
  get "/search", to: "players#search"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :winner, class_name: :Player, optional:  true
  belongs_to :loser, class_name: :Player, optional:  true
  belongs_to :p1, class_name: :Player, optional:  true
  belongs_to :p2, class_name: :Player, optional:  true
  belongs_to :round

  def who_won(winnerid)
    winner = Player.find(winnerid)
    if self.p2 == winner
      winner.add_point
      self.update(winner: winner, loser: self.p1, status:"Completed")
    elsif self.p1 == winner
      winner.add_point
      self.update(winner: winner, loser: self.p2, status:"Completed")
    end
    self.round.check_done
  end



end

app/models/player.rb
class Player < ApplicationRecord
  has_many :games_as_p1, class_name: :Game, foreign_key: :p1_id
  has_many :games_as_p2, class_name: :Game, foreign_key: :p2_id
  has_many :rounds, through: :games
  has_many :tournaments, through: :rounds
  validates :nickname, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def name
    self.first_name.capitalize + " " + self.last_name.capitalize
  end

  def games
    self.games_as_p1 + self.games_as_p2
  end

  def win?(game)
    if game.winner == self
      "won"
    elsif game.loser == self
      "lost"
    else
      "playing"
    end
  end

  def self.active_players
    self.all.select do |player|
      player.active
    end
  end

  def add_point
    self.update(points: (self.points + 1))
  end

  def self.ranks
    ranks = []
    ranks = Player.active_players.sort_by {|player| player.points}
    return ranks.reverse
  end

  def game_win_percentage
    games = self.games.select do |game|
      game.status == "Completed"
    end
    games_played = games.count
    if games_played == 0
      "No Stats"
    else
      games_won = 0
      games.each do |game|
        if game.winner == self
          games_won+=1
        end
      end

      percent = ( games_won.to_f/games_played)*100
    return percent.to_s + "%"
    end
  end

  def tour_win_percentage
    tourn = self.games.select do |game|
      game.round.tournament.status == "Completed"
    end
    tour_played = tourn.uniq.count
    if tour_played == 0
      "No Stats"
    else
      tour_won = 0
      tourn.uniq.each do |tour|
        if tour.winner_id == self.id
          tour_won+=1
        end
      end

      percent = ( tour_won.to_f/tour_played)*100
      return percent.to_s + "%"
    end
  end

  def default_image
    arr = ["cat1.jpg", "cat2.jpg", "cat3.jpg", "cat4.jpg", "cat7.jpeg", "dog1.png", "dog2.png", "dog3.jpg",
            "dog4.jpg", "dog6.jpg", "horse.jpg", "lizard.jpg", "monkey.jpg", "squirrel.jpg"]
    self.img_url = arr.sample
  end


end

app/models/round.rb
class Round < ApplicationRecord
  has_many :games, dependent: :destroy
  has_many :players, through: :games
  belongs_to :tournament

  def check_done
    t = self.games.all? {|game| game.status == "Completed"}
    if t && self.games.size == 1
      self.tournament.set_winner(self.games.last.winner.id)
      self.tournament.complete_torn
      # byebug
    elsif t
      self.complete_round
      self.tournament.new_round(self.num)
    end

  end

  def complete_round
    self.update(status: "Completed")
  end

  def add_games_to_next_round(winners)

    if winners.size % 2 == 0

      number_of_games = winners.size / 2
      number_of_games.times do

        g = Game.create(p1: winners.shift, p2: winners.shift, status: "pending", round: self)

      end
    end

  end


  def get_winners
    array = []
    self.games.each do |game|
      array << game.winner
    end
    return array

  end

end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :rounds, dependent: :destroy
  has_many :games, through: :rounds
  has_many :players, through: :games
  belongs_to :user
  validates :num_players, presence: true
  validates :num_players, inclusion: { in: [2, 4, 8, 16, 32, 64, 128], message: "must be 2, 4, 6, 8, 16, 32, 64, or 128."}
  validates :name, presence: true, uniqueness: true
  validate :player_number

  cattr_accessor :player_numbers



  def new_round(num)

      winners = self.rounds.last.get_winners
      r = Round.create(num: (num+1), tournament: self, status: "pending")
      r.add_games_to_next_round(winners)



  end
  def get_winner
    winner = self.winner_id
    winner = Player.find(winner)
    return winner
  end

  def set_winner(id)
    winner = Player.find(id)
    self.update(winner_id: winner.id)
  end

  def complete_torn
    self.rounds.last.update(status: "Completed")
    self.update(status: "Completed")
  end

  def player_number
    if Tournament.player_numbers == false
      errors.add(:num_players, ": The number of players selected is inaccurate")
    end
  end

  def get_all_winner
    winner = {}
    self.rounds.each_with_index do |round, i|
      name = "round_"+i.to_s
      winner[name] = {}
      round.games.each_with_index do |game, i|
        gname = "game_"+i.to_s
        winner[name][gname] = game.winner.name
      end
    end
    return winner
  end

  def get_all_loser
    # loser =[]
    loser = {}
    self.rounds.each_with_index do |round, i|
      name = "round_"+i.to_s
      loser[name] = {}
      round.games.each_with_index do |game, i|
        gname = "game_"+i.to_s
        loser[name][gname] = game.loser.name
      end
    end
    return loser
  end




end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tournaments, dependent: :destroy
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :get_game, only: [:show, :set_winner]
  before_action :authorized

  def show

  end

  def set_winner
    if @game.p1.id == params[:format].to_i
      @game.who_won( params[:format])
    elsif @game.p2.id == params[:format].to_i
      @game.who_won( params[:format])
    end

    redirect_to @game.round.tournament
  end

  private

  def get_game
    @game = Game.find(params[:id])
  end

end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  before_action :authorized

  def index
    @ranks = Player.ranks

  end

end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :get_round, only: [:show]
  before_action :authorized

  def show

  end

  private

  def get_round
    @round = Round.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authorized

  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)

    if @user.valid?
        @user.save
        session['user_id'] = @user.id
        redirect_to tournaments_path
    else
        render :new
    end


  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daphs_helper.rb
module DaphsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PingPong</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="semantic.min.css">
    <link rel="stylesheet" type="text/css" href="semantic.css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Tulpen+One|Wire+One" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="application.css">

  </head>

  <body>
    <nav>
      <ul class="menu-nav-bar">
        <li class="menu-item"><%= link_to image_tag("logo.png", style: "width:100px; height:38px;", border: 0), root_path %></li>
        <li class="menu-item"><%= link_to "  Create a Tournament  ", new_tournament_path, class: "nav-item" %></li>
        <li class="menu-item"><%= link_to "  Create a Player  ", new_player_path, class: "nav-item" %></li>
        <li class="menu-item"><%= link_to "  Your Tournaments  ", tournaments_path, class: "nav-item" %></li>
        <li class="menu-item"><%= link_to "  All Players  ", players_path, class: "nav-item" %></li>
        <li class="menu-item"><%= link_to "  Player Ranks  ", ranks_path, class: "nav-item" %></li>

        <li class="menu-item">
          <% if session[:user_id] %>
            <%= link_to "Log out #{current_user.username}", logout_path, method: "delete", class: "nav-item" %>
          <% else %>
            <%= link_to "Log in", login_path, class: "nav-item" %>
          <% end %>
        </li>
      </ul>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/shared/_error_list.html.erb
<% if new_object.errors.any? %>
  <div class="box" id="error_explanation">
    <h2>
      <%= pluralize(new_object.errors.count, "error") %> prohibited this user from being saved!
    </h2>
    <ul>
      <% new_object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>